package com.sky.service.impl;

import com.github.pagehelper.PageHelper;
import com.sky.constant.MessageConstant;
import com.sky.constant.StatusConstant;
import com.sky.context.BaseContext;
import com.sky.dto.DishDTO;
import com.sky.dto.DishPageQueryDTO;
import com.sky.entity.Dish;
import com.sky.entity.DishFlavor;
import com.sky.exception.DeletionNotAllowedException;
import com.sky.mapper.DishFlavorMapper;
import com.sky.mapper.DishMapper;
import com.sky.mapper.SetmealDishMapper;
import com.sky.result.PageResult;
import com.sky.service.DishService;
import com.sky.vo.DishVO;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

@Service
@Slf4j
public class DishServiceImpl implements DishService {
    @Autowired
    private DishMapper dishMapper;
    @Autowired
    private DishFlavorMapper dishFlavorMapper;
    @Autowired
    private SetmealDishMapper setmealDishMapper;

    /**
     * Add dish and save its flavors
     *
     * @param dishDTO
     */
    @Override
    @Transactional
    public void saveWithFlavor(DishDTO dishDTO) {
        Dish dish = new Dish();
        BeanUtils.copyProperties(dishDTO, dish);

        // Insert a record into the dish table
        dishMapper.insert(dish);

        // Get the primary key id generated by insert
        Long dishId = dish.getId();

        List<DishFlavor> flavors = dishDTO.getFlavors();
        if (flavors != null && !flavors.isEmpty()) {
            for (DishFlavor flavor : flavors) {
                // Insert n records into the flavor table
                flavor.setDishId(dishId);
            }
            dishFlavorMapper.insertBatch(flavors);
        }
    }

    /**
     * Paginated dish query
     *
     * @param dishPageQueryDTO
     * @return
     */
    @Override
    public PageResult pageQuery(DishPageQueryDTO dishPageQueryDTO) {
        PageHelper.startPage(dishPageQueryDTO.getPage(), dishPageQueryDTO.getPageSize());

//        Page<DishVO> page = dishMapper.pageQuery(dishPageQueryDTO);
//        return new PageResult(page.getTotal(),page.getResult());

        List<DishVO> dishVOList = dishMapper.pageQuery(dishPageQueryDTO);

        PageResult pageResult = new PageResult();
        pageResult.setTotal(dishVOList.size());
        pageResult.setRecords(dishVOList);

        return pageResult;
    }

    /**
     * Delete dish
     *
     * @param ids
     */
    @Override
    //transactional consistency
    @Transactional
    public void deleteBatch(Long[] ids) {
        //check whether the dish is currently on sale
        for (Long id: ids) {
            Dish dish = dishMapper.getById(id);
            if (dish == null) {
                //id no longer exists (already deleted / stale client state), skip it
                log.warn("Dish id {} not found, skipping deletion", id);
                continue;
            }
            if (Objects.equals(dish.getStatus(), StatusConstant.ENABLE)) {
                //dishes on sale cannot be deleted
                throw new DeletionNotAllowedException(MessageConstant.DISH_ON_SALE);
            }
        }

        //check whether the dish is associated with a set meal
        List<Long> setmealIdsByDishIds = setmealDishMapper.getSetmealIdsByDishIds(Arrays.asList(ids));
        if (setmealIdsByDishIds != null && !setmealIdsByDishIds.isEmpty()) {
            //dish is linked with a set meal, cannot be deleted
            throw new DeletionNotAllowedException(MessageConstant.DISH_LINKED_TO_SETMEAL);
        }

        //delete the dish data from the dish table
//        for (Long id: ids) {
//            dishMapper.deleteById(id);
//
//            //delete the flavor data associated with the dish
//            dishFlavorMapper.deleteByDishId(id);
//        }
        //batch delete dishes by IDs
        //sql: delete from dish where id in (?,?,?)
        dishMapper.deleteByIds(Arrays.asList(ids));

        //batch delete flavors associated with dish by dish IDs
        //sql: delete from dish_flavor where dish_id in (?,?,?)
        dishFlavorMapper.deleteByDishIds(ids);

    }

    /**
     * Query dish by id
     *
     * @param id
     * @return
     */
    @Override
    public DishVO getByIdWithFlavor(Long id) {
        Dish dish = dishMapper.getById(id);
        DishVO dishVO = new DishVO();

        if (dish != null) {
            BeanUtils.copyProperties(dish, dishVO);
            // Query the flavor data corresponding to the dish, from the dish_flavor table
            List<DishFlavor> flavors = dishFlavorMapper.getByDishId(id);
            dishVO.setFlavors(flavors);
        }

        return dishVO;
    }

    /**
     * Update dish and its flavors
     *
     * @param dishDTO
     */
    @Override
    public void updateWithFlavor(DishDTO dishDTO) {
        Dish dish = new Dish();
        BeanUtils.copyProperties(dishDTO, dish);

        // Update basic dish table info
        dishMapper.update(dish);

        // Delete existing flavor data
        dishFlavorMapper.deleteByDishId(dish.getId());

        List<DishFlavor> flavors = dishDTO.getFlavors();
        if (flavors != null && !flavors.isEmpty()) {
            // Batch insert n records
            flavors.forEach(flavor -> {
                flavor.setDishId(dish.getId());
            });
            dishFlavorMapper.insertBatch(flavors);
        }
    }

    /**
     * Enable or disable dish
     *
     * @param status
     * @param id
     */
    @Override
    @Transactional
    public void startOrStop(Integer status, Long id) {
        Dish dish = Dish.builder()
                .id(id)
                .status(status)
                .updateTime(LocalDateTime.now())
                .updateUser(BaseContext.getCurrentId())
                .build();

        dishMapper.update(dish);
    }

    /**
     * Query dishes by category id
     *
     * @param categoryId
     * @return
     */
    @Override
    public List<Dish> list(Long categoryId) {
        return dishMapper.getListById(categoryId);
    }

    /**
     * Query dishes and flavors by condition
     * @param dish
     * @return
     */
    public List<DishVO> listWithFlavor(Dish dish) {
        List<Dish> dishList = dishMapper.list(dish);

        List<DishVO> dishVOList = new ArrayList<>();

        for (Dish d : dishList) {
            DishVO dishVO = new DishVO();
            BeanUtils.copyProperties(d,dishVO);

            // Query the corresponding flavors by dish id
            List<DishFlavor> flavors = dishFlavorMapper.getByDishId(d.getId());

            dishVO.setFlavors(flavors);
            dishVOList.add(dishVO);
        }

        return dishVOList;
    }

    /**
     * Query dishes by category id
     *
     * @param categoryId
     * @return
     */
    // @Override
    // public List<Dish> list(Long categoryId) {
    //     // return List.of();
    // }

    /**
     * Query dishes and flavors by condition
     *
     * @param dish
     * @return
     */
    // @Override
    // public List<DishVO> listWithFlavor(Dish dish) {
    //     // return List.of();
    // }
}
