server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${palette.datasource.driver-class-name}
      url: jdbc:mysql://${palette.datasource.host}:${palette.datasource.port}/${palette.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${palette.datasource.username}
      password: ${palette.datasource.password}
  redis:
    host: ${palette.redis.host}
    port: ${palette.redis.port}

mybatis:
  #mapper config files
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.palette.entity
  configuration:
    #enable camel case mapping
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      palette:
        mapper: debug
        service: info
        controller: info

palette:
  jwt:
    # secret key used when signing/encrypting the jwt
    admin-secret-key: itcast
    # jwt expiration time
    admin-ttl: 7200000
    # name of the token passed in from the frontend
    admin-token-name: token
    # user jwt configuration
    user-secret-key: itcast
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${palette.alioss.endpoint}
    access-key: ${palette.alioss.access-key}
    secret-key: ${palette.alioss.secret-key}
    bucket-name: ${palette.alioss.bucket-name}
  stripe:
    secret-key: ${palette.stripe.secret-key}
    success-url: ${palette.stripe.success-url}
    cancel-url: ${palette.stripe.cancel-url}


